version: "3"
services:
  postgres:
    image: "postgres:14.1-alpine3.15"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      args:
        POSTGRES_HOST: "postgres"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: on-failure
volumes:
  postgres-data:
