version: "3.8"
services:
  postgres:
    image: "postgres:14.4-alpine3.16"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 1s
      start_period: 3s
  api:
    build: .
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ./health-check
      interval: 15s
      timeout: 1s
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
volumes:
  postgres-data:
