version: "3"
services:
  postgres:
    image: "postgres:14.1-alpine3.15"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  api:
    build:
      context: .
      args:
        POSTGRES_HOST: "postgres"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test123"
      POSTGRES_DB: "consents"
      PORT: "8080"
    depends_on:
      - postgres
    restart: on-failure
