version: "3"
services:
  postgres:
    image: "postgres:14.4-alpine3.16"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  api:
    build:
      context: .
      args:
        POSTGRES_HOST: "postgres"
        POSTGRES_PORT: "${POSTGRES_PORT}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: on-failure
volumes:
  postgres-data:
