version: '3.8'

services:
  db:
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1-bullseye
        NODE_VERSION: "lts/*"
    command: sleep infinity
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${PORT}
    ports:
       - "${PORT}:${PORT}"
    volumes:
      - ..:/workspace:cached
volumes:
  postgres-data:
