name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Test
        run: |
          go get -d -t ./...
          go test ./... -coverprofile=coverage.out
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
