name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Test
        run: |
          go get -t ./...
          go test ./... -coverprofile=coverage.out
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Image Meta
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short,prefix=
          images: ${{ secrets.DOCKERHUB_USERNAME }}/consents-api-go
      - name: Push Image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
